# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

# See:
# https://wemake-python-styleguide.rtfd.io/en/latest/pages/usage/integrations/nitpick

# This file is included into base-preset.

# These settings set in order to work in conjunction with 'Black'
# Read more https://pycqa.github.io/isort/docs/configuration/profiles.html
["setup.cfg".isort]
# These values should be placed inside `setup.cfg` in your repo:
profile = "black"
line_length = 120