# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

# These values should be placed inside `setup.cfg` in your repo:
["setup.cfg".pylint.format]
max-line-length = 120
